### ISSUE TITLE
Create a dashboard for seller to keep track of auctions.

### ISSUE THREAD

**Issue by HarshitRV** [Hritvik-Mohan/Auction-Project#38]

**Comment by HarshitRV** [comment]
Share the figma design here after you are done working on it @Hritvik-Mohan for Dashboard.

**Comment by Hritvik-Mohan** [comment]
This is already done at #119

**Comment by Hritvik-Mohan** [comment]
Here's the [figma link.](https://www.figma.com/file/v9NkRLfYRsDssey0rX2p6X/Untitled?node-id=0%3A1) 🔗
