### ISSUE TITLE
Set default time zone to IST 

### ISSUE THREAD

**Issue by Hritvik-Mohan** [Hritvik-Mohan/Auction-Project#77]

**Comment by Hritvik-Mohan** [comment]
It's not fixed. It still says OFFLINE.
![image](https://user-images.githubusercontent.com/25386810/173189761-09f5ff8a-b40e-415c-bbd2-4484df6e162c.png)

**Comment by Hritvik-Mohan** [comment]
Just fix the default time zone to IST, or convert the default time zone i.e. GMT on the production server to the local timezone.

**Comment by HarshitRV** [comment]
Issue resolved in commit [d71bf72](https://github.com/Hritvik-Mohan/Auction-Project/commit/d71bf72af5d86f946df1bfa71243d1393eb787bd)
